services:
  schedule_tracker:
    build: .
    container_name: lucos_schedule_tracker
    ports:
      - ${PORT:-8024}:${PORT:-8024}
    environment:
      - PORT
    image: lucas42/lucos_schedule_tracker:${VERSION:-latest}
    volumes:
      - "db:/var/lib/schedule_tracker/"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT:-8024}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  test:
    build: .
    container_name: lucos_schedule_tracker_test
    image: lucas42/lucos_schedule_tracker:${VERSION:-latest}
    command: ruby database_test.rb
    profiles:
      - test

volumes:
  db: