FROM ruby:3.3.6-alpine3.19
ARG VERSION
ENV VERSION=$VERSION

WORKDIR /usr/src/app

COPY src/Gemfile src/Gemfile.lock ./
RUN bundle config set --local frozen true && bundle install

COPY src/*.rb .
COPY test/ ./test/
