version: 2.1
orbs:
  lucos: lucos/deploy@0

jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: docker compose --profile test up test --build --exit-code-from test

  lint:
    docker:
      - image: cimg/ruby:3.3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd src && bundle install
      - run:
          name: Run RuboCop
          command: BUNDLE_GEMFILE=src/Gemfile bundle exec rubocop

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - lint
      - lucos/build:
          serial-group: << pipeline.project.slug >>/build/<< pipeline.git.branch >>
      - lucos/deploy-avalon:
          serial-group: deploy-avalon
          requires:
            - test
            - lint
            - lucos/build
          filters:
            branches:
              only:
                - main
