source 'https://rubygems.org'

gem 'sqlite3', '~> 2.0', '>= 2.0.0'

group :test do
	gem 'minitest', '~> 5.0'
	gem 'minitest-reporters', require: false
	gem 'simplecov', require: false
end

group :lint do
	gem 'rubocop', require: false
end
